#--
# DO NOT MODIFY!!!!
# This file is automatically generated by rex 1.0.5
# from lexical definition file "lib/rparser/lexer.rex".
#++

require 'racc/parser'
class Rparser::Parser < Racc::Parser
  require 'strscan'

  class ScanError < StandardError ; end

  attr_reader   :lineno
  attr_reader   :filename
  attr_accessor :state

  def scan_setup(str)
    @ss = StringScanner.new(str)
    @lineno =  1
    @state  = nil
  end

  def action
    yield
  end

  def scan_str(str)
    scan_setup(str)
    do_parse
  end
  alias :scan :scan_str

  def load_file( filename )
    @filename = filename
    open(filename, "r") do |f|
      scan_setup(f.read)
    end
  end

  def scan_file( filename )
    load_file(filename)
    do_parse
  end


  def next_token
    return if @ss.eos?
    
    # skips empty actions
    until token = _next_token or @ss.eos?; end
    token
  end

  def _next_token
    text = @ss.peek(1)
    @lineno  +=  1  if text == "\n"
    token = case @state
    when nil
      case
      when (text = @ss.scan(/\n/))
        ;

      when (text = @ss.scan(/\#.*(?=$)/))
         action { [:comment, text] }

      when (text = @ss.scan(/,/))
         action { [:comma, text] }

      when (text = @ss.scan(/[a-zA-Z][a-zA-Z\-_]+/))
         action { [:keyword, text] }

      when (text = @ss.scan(/\s+/))
        ;

      when (text = @ss.scan(/\d{4}\/\d{2}\/\d{2}\s\d{2}\:\d{2}\:\d{2}/))
         action { [:datetime, text] }

      when (text = @ss.scan(/[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}/))
         action { [:macaddr, text] }

      when (text = @ss.scan(/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/))
         action { [:ipaddress, text] }

      when (text = @ss.scan(/\d+/))
         action { [:integer, text] }

      when (text = @ss.scan(/;/))
         action { [:semicolon, text] }

      when (text = @ss.scan(/{/))
         action { [:lcurly, text] }

      when (text = @ss.scan(/}/))
         action { [:rcurly, text] }

      when (text = @ss.scan(/\"[^"]*\"/))
         action { [:string, text] }

      else
        text = @ss.string[@ss.pos .. -1]
        raise  ScanError, "can not match: '" + text + "'"
      end  # if

    else
      raise  ScanError, "undefined state: '" + state.to_s + "'"
    end  # case state
    token
  end  # def _next_token

end # class
